### ISSUE TITLE
Processing JSON array trigger Passed array keys must be a string. Maybe consider using "array_to_rows()" function? error

### ISSUE THREAD

**Issue by yfktn** [flow-php/flow#1210]
I apologize if this is a basic question.

I'm having trouble processing a JSON file where an array lacks key names. Below is a sample of my data:

```json
{
  "draw": null,
  "recordsTotal": 12659,
  "recordsFiltered": 12659,
  "data": [
      [
          "647",
          "Margie Rowe",
          "emailfakefakedata89479@mail.fake.co",
          "E-Purchasing",
          "July 9, 2024",
          "June 1, 2024",
          "Rp. 15,284,386",
          "101753",
          "0",
          "Procurement of Goods",
          "true",
          "true",
          "APBD",
          "52049496",
          "June 1, 2024",
          ""
      ],
      [
          "165",
          "Margie Rowe",
          "emailfakefakedata29002@mail.fake.co",
          "Self-management",
          "March 25, 2024",
          "March 1, 2024",
          "Rp. 81,778,000",
          "60276",
          "1",
          "",
          "false",
          "false",
          "APBD",
          "36070200",
          "December 1, 2024",
          "Type I"
      ]
  ]
}
```

When I attempt to retrieve the array inside `/data`, I encounter the following error message:  
`Passed array keys must be a string. Maybe consider using "array_to_rows()"`.

Here’s the basic code I’m using:

```php
data_frame()
    ->read(
        from_json(__DIR__ . "/user-data.json", '/data')
    )
    ->write(to_output(false))
    ->run();
```

And here is the full error message:

```
#0 /Users/yanf/Projects/belajarjsonmysql/vendor/flow-php/etl/src/Flow/ETL/DSL/functions.php(1063): Flow\ETL\DSL\array_to_row(Array, Object(Flow\ETL\Row\Factory\NativeEntryFactory), Object(Flow\Filesystem\Partitions), NULL)
#1 /Users/yanf/Projects/belajarjsonmysql/vendor/flow-php/etl-adapter-json/src/Flow/ETL/Adapter/JSON/JSONMachine/JsonExtractor.php(44): Flow\ETL\DSL\array_to_rows(Array, Object(Flow\ETL\Row\Factory\NativeEntryFactory), Object(Flow\Filesystem\Partitions), NULL)
#2 [internal function]: Flow\ETL\Adapter\JSON\JSONMachine\JsonExtractor->extract(Object(Flow\ETL\FlowContext))
#3 /Users/yanf/Projects/belajarjsonmysql/vendor/flow-php/etl/src/Flow/ETL/Pipeline/SynchronousPipeline.php(46): Generator->valid()
#4 /Users/yanf/Projects/belajarjsonmysql/vendor/flow-php/etl/src/Flow/ETL/DataFrame.php(738): Flow\ETL\Pipeline\SynchronousPipeline->process(Object(Flow\ETL\FlowContext))
#5 /Users/yanf/Projects/belajarjsonmysql/convert-rup-terumumkan.php(27): Flow\ETL\DataFrame->run()
#6 {main}
  thrown in /Users/yanf/Projects/belajarjsonmysql/vendor/flow-php/etl/src/Flow/ETL/DSL/functions.php on line 1002
```

Could someone please guide me on how to resolve this issue? Thank you!

**Comment by norberttech** [comment]
hey @yfktn this looks like a bug, I'm going to get back to you later with some answers once I take a closer look into this, thanks for reporting!

**Comment by yfktn** [comment]
Thank you. I'm looking forward to your update.

**Comment by norberttech** [comment]
hey @yfktn I believe I found a source of this bug, could you please try it with the 1.x-dev version and let me know if it's working for you?

**Comment by yfktn** [comment]
Yes, this fix works as expected. Thank you.

**Comment by norberttech** [comment]
aaesome 👌
